### PR TITLE
data frame helper functions for ease of use

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by antiiles** [comment]
change PCA_background to just 'backgound'

**Comment by antiiles** [comment]
separate style in plotting from the rest of the code by spacing it out with line breaks/comments. Looks cleaner

**Comment by CJ-Wright** [comment]
Use background from df for processing (eg. 5)

**Comment by CJ-Wright** [comment]
Remove confidence interval

**Comment by CJ-Wright** [comment]
12x5 fig size

**Comment by CJ-Wright** [comment]
Pull composition from dataframe, composition column.

**Comment by CJ-Wright** [comment]
Support re-running of processing.

**Comment by CJ-Wright** [comment]
Pull refinement info from pickle and write to CSV.

**Comment by CJ-Wright** [comment]
@antiiles Can I get some more description on the re-running of the analysis?

**Comment by antiiles** [comment]
The processing takes the gr's and applies a fit recipe that we create for each data frame entry. The refined parameters are saved alongside the other entries

**Comment by antiiles** [comment]
re-running is the last priority after plotting the pickle contents

**Comment by CJ-Wright** [comment]
Feel free to push to this PR.

**Comment by sbillinge** [comment]
This PR is replaced by #12 so closing here.

**Pull request closed without merging**
